version: '3.3'

services:
  db:
    build: mysql/
    restart: always
    volumes:
      - my-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: public
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  spring:
    depends_on:
      - db
    build: spring/
    restart: always
    ports:
      - "8080:8080"
    links:
      - db
volumes:
  my-data:

# docker-compose up
